### ISSUE TITLE
Suggestion: allow back predicted shots

### ISSUE THREAD

**Issue by Tapetepato** [StatTrack/StatTrack.github.io#33]
I know they were removed because "you are not actually killing them" but its because people combatlog, and the server made it so its actually a kill, maybe you just got 1 shot on him while he was lagging out, or changing server, but there are a lot of times where they combatlog to avoid getting the last shot, so, since its actually a kill, imo it should be accepted.

**Comment by JexeI** [comment]
Predicted shots are not only inaccurate, but also sometimes false. When a player gets hit by an arrow, or any other projectile and logs out, PGM does not calculate the distance between where you shot the arrow, and where the person who got hit was. Instead, it calculates from where you were when you shot a bow, and where the player **last logged out**. This might make sense but consider this: Player A shoots player B in scrap mettle, knocking player B into a scorebox. Player B teleports across the map to their spawn, and while still tagged in combat, logs out. Player A is then awarded the predicted kill, and earns a 371 block shot.
