### ISSUE TITLE
Mistakes on some maps, shot, and small typing errors

### ISSUE THREAD

**Issue by Tapetepato** [StatTrack/StatTrack.github.io#34]
Aeruhohoho and Arbaro Blitzmas should be on Normal Blitz on Christmas section, but its on Blitz: Rage Christmas map.
My shot on Airship Battles (95 blocks) was actually on Airship Ascendance (a very similar map made by last i think)
There's a 125 blocks shot by Nyco29 on Fort Beverstone, but since theres no post of it and its the same that the shot under it, i think you made a mistake and added that instead of my 58 blocks shot on there (https://oc.tc/forums/topics/5374d3a812ca951e4f000549?page=65#5499b118c29635d603000a7b)
My 70 blocks on SandBox was actually a 70 blocks shot (https://oc.tc/forums/topics/5374d3a812ca951e4f00054)
MeMyselfandGhost shot on An Overcast Christmas wasn't 42 blocks, it was 49 (https://oc.tc/forums/topics/5374d3a812ca951e4f000549?page=63#548b6e065f35b99a7c0038d4)
I have 2 records on Dwyer Hill,Antiquis (theres supposed to be 1 shot per person on each map)
On Pandemonium, capyv's shot is missing an ) at the end.

**Comment by Nyco29** [comment]
Fixed
