### ISSUE TITLE
Longest/shortest matches need rebranding as well (and a forum thread?)

### ISSUE THREAD

**Issue by MrTheSharpie** [StatTrack/StatTrack.github.io#58]

**Comment by CrazyCreeper521** [comment]
May not end up tracking this, will rebrand and add thread if I decide to keep it

**Comment by CrazyCreeper521** [comment]
Updated the year on all pages. However, the longest/shortest match project will not continue, and will be turned into something else. I don't want to rebrand yet, since I don't want to make more work for myself when updating those pages when I add the new stat records.
