### ISSUE TITLE
crafatar.com doesn't track the hat layer on skins

### ISSUE THREAD

**Issue by CrazyCreeper521** [StatTrack/StatTrack.github.io#68]
https://crafatar.com/avatars/Crazy_ - no hat layer
https://minotar.net/helm/Crazy_/150.png - hat layer

The crafatar.com image is used on the new profiles. I don't want to mess around with the code and break anything, so I'll just let you know via this issue Mitc.h Anyways, minator.net seems to track the hat layers, so preferably that would be used over crafatar for the profile pictures on the new profile pages.

**Comment by mitchiiii** [comment]
We can change the profiles to use Minotar avatars, however it doesn't appear to accept UUIDs which are being used for record avatars.

**Comment by mitchiiii** [comment]
https://github.com/StatTrack/StatTrack.github.io/commit/118d72a0819247d6b9972cd6e5509c8d7bf3efbc

**Comment by CrazyCreeper521** [comment]
Ok, so records are still using crafatar? Sounds good
