### ISSUE TITLE
Drop down link incorrect on the staff profiles

### ISSUE THREAD

**Issue by CrazyCreeper521** [StatTrack/StatTrack.github.io#69]
Using the drop down menu to access the records from the staff profile pages redirects you to http://stattrack.github.io/staff/lifeboat/records/bow (etc for the rest)

It should be http://stattrack.github.io/lifeboat/records/bow (and again, the rest of the drop down menu is redirects you wrongly as well)

**Comment by mitchiiii** [comment]
https://github.com/StatTrack/StatTrack.github.io/commit/8aa1e9c1b7968c86ed03880ea6cdf5a85fc75b31
